version: '3.7'

services:
  web:
    image: news_site_web
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    command: /start
    depends_on:
      - redis
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=news_site_dev

  redis:
    image: redis:5-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: news_site_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: news_site_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: news_site_celey_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data: