#!/bin/bash

set -o errexit
set -o nounset

worker_ready(){
  celery -A news_site inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers are not available'
  sleep 1
done
>&2 echo 'Celery workers are available'

flower --app=news_site --broker="${CELERY_BROKER}"